export interface TopCurrency {
  code: string;
  name: string;
}

export const topCurrencies: TopCurrency[] = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "KRW", name: "South Korean Won" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "INR", name: "Indian Rupee" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "ZAR", name: "South African Rand" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "DKK", name: "Danish Krone" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "THB", name: "Thai Baht" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "AED", name: "UAE Dirham" },
  { code: "COP", name: "Colombian Peso" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "RON", name: "Romanian Leu" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "ISK", name: "Icelandic Krona" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "MMK", name: "Myanmar Kyat" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "CRC", name: "Costa Rican Colon" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "LAK", name: "Lao Kip" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "MNT", name: "Mongolian Tugrik" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "PYG", name: "Paraguayan Guarani" },
  { code: "SVC", name: "Salvadoran Colon" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "BWP", name: "Botswana Pula" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "AOA", name: "Angolan Kwanza" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BZD", name: "Belize Dollar" },
];

export const topCurrencyCodes = topCurrencies.map(currency => currency.code);